import type {
  CoreAction,
  DaoPath,
  Effect,
  Ending,
  EventChoice,
  GameEvent,
  GameItem,
  OriginId,
  VowId,
} from './types';

const choice = (label: string, result: string, effect: Effect): EventChoice => ({ label, result, effect });
const event = (
  id: string,
  title: string,
  text: string,
  action: CoreAction,
  first: EventChoice,
  second: EventChoice,
  paths?: DaoPath[],
  minRealm?: number,
): GameEvent => ({ id, title, text, actions: [action], choices: [first, second], paths, minRealm });

export const EVENTS: GameEvent[] = [
  event('insight-thunder-wall', '雷壁留痕', '暴雨劈开崖壁，焦黑裂痕竟与体内灵脉遥相呼应。', '悟道',
    choice('以神魂摹写', '雷意刺入识海，你记住了那一瞬。', { insight: 8, soul: -6, harmony: 3 }),
    choice('静观雨歇', '不争一瞬，反见雷霆生灭。', { insight: 4, stability: 5 })),
  event('insight-old-turtle', '玄龟负图', '潭底老龟浮出水面，甲纹像一幅残缺道图。', '悟道',
    choice('拓下甲纹', '古纹入纸，灵思纷至。', { insight: 7, item: 'turtle-rubbing' }),
    choice('放归深潭', '玄龟回首，赠你一缕温和魂息。', { soul: 9, karma: 4 })),
  event('insight-star-river', '星河倒悬', '夜空在灵泉中倒映，群星的轨迹似乎有迹可循。', '悟道',
    choice('彻夜推演', '天明时，你眼中仍有星轨流转。', { insight: 10, soul: -8 }),
    choice('只取一星', '少即是多，一点星芒稳住道心。', { insight: 5, stability: 6 })),
  event('insight-broken-bell', '残钟无声', '荒寺铜钟已裂，却在你的神魂中发出沉鸣。', '悟道',
    choice('叩问残钟', '无声胜有声，识海荡开层层波纹。', { insight: 9, stability: -4 }),
    choice('修补钟身', '附近山民记住了你的善举。', { insight: 3, reputation: 5, karma: 3 })),
  event('insight-cloud-dragon', '云中龙脊', '长云横山，宛如苍龙舒展脊骨。', '悟道',
    choice('追云百里', '你踏遍七峰，终得云势。', { insight: 8, health: -4 }),
    choice('原地入定', '云去而意留，神魂愈发澄明。', { insight: 5, soul: 5 })),
  event('insight-market-noise', '市井万声', '叫卖、争吵与笑声交织，红尘也有自己的律动。', '悟道',
    choice('听尽百声', '万声归一，你悟得众生之纹。', { insight: 7, influence: 3 }),
    choice('替人解纷', '一场争端消弭于无形。', { reputation: 7, karma: 4 })),
  event('insight-void-mirror', '虚镜照心', '古镜不照形貌，只映出你最深的执念。', '悟道',
    choice('直视执念', '镜面破碎，执念却化作道火。', { insight: 11, stability: -7 }),
    choice('蒙上古镜', '知止也是一种清醒。', { harmony: 8, stability: 8 })),
  event('insight-path-echo', '道途回响', '行功之际，你所选的道途发出只有自己能听见的回响。', '悟道',
    choice('循声深入', '回响最终与心跳重合。', { insight: 9, soul: -5 }),
    choice('重审初心', '你没有走得更快，却走得更稳。', { harmony: 9, karma: 2 })),

  event('engrave-silver-sand', '银砂凝纹', '一匣星银砂可令道纹更锋锐，也可能侵蚀经脉。', '凝纹',
    choice('掺入银砂', '纹路银芒流转，代价也刻进血肉。', { harmony: 7, health: -6, item: 'star-silver' }),
    choice('守正凝刻', '道纹朴素无华，却与神魂无隙。', { harmony: 5, stability: 4 })),
  event('engrave-ghost-fire', '鬼火淬纹', '坟丘鬼火绕着新生道纹盘旋，似在等待一念许可。', '凝纹',
    choice('引火淬炼', '幽焰烧去杂念，也灼伤了一缕魂魄。', { insight: 6, soul: -8, harmony: 5 }),
    choice('诵诀超度', '鬼火散作磷光，夜色重归安宁。', { karma: 7, stability: 6 })),
  event('engrave-rain-script', '雨书天成', '凝纹时骤雨穿窗，每滴水珠都沿着纹路滚落。', '凝纹',
    choice('借雨续笔', '天水补足了最后一处缺口。', { harmony: 8, qi: 8 }),
    choice('封室独成', '拒绝外力令你的纹心更坚。', { stability: 7, insight: 3 })),
  event('engrave-blood-choice', '血墨之问', '古法称心血为最佳纹墨，石案上的刻刀寒光凛冽。', '凝纹',
    choice('以血为墨', '血与纹相合，威势骤增。', { health: -12, harmony: 10, reputation: 2 }),
    choice('弃用邪法', '力量未必来自牺牲。', { karma: 8, insight: 5 })),
  event('engrave-master-shadow', '祖师留影', '纹成刹那，陌生祖师的虚影在识海中一闪而过。', '凝纹',
    choice('追问虚影', '虚影只留下一式残诀。', { insight: 9, soul: -7 }),
    choice('稽首送别', '一礼之后，道纹自行圆融。', { harmony: 10, reputation: 3 })),
  event('engrave-split-pattern', '双纹歧路', '新纹分出相斥的两笔：一笔主杀，一笔主生。', '凝纹',
    choice('留下杀笔', '锐意贯穿全纹。', { qi: 12, karma: -5, influence: 4 }),
    choice('留下生笔', '温润气息滋养经络。', { health: 10, karma: 5 })),
  event('engrave-resonance', '诸纹共鸣', '旧纹与新纹相互激荡，洞府石屑簌簌而落。', '凝纹',
    choice('压下共鸣', '你稳住了每一道纹路。', { stability: 8, control: 4 }),
    choice('任其齐鸣', '轰鸣之后，所有道纹更见通透。', { harmony: 12, soul: -6 })),

  event('duel-river-swordsman', '江上剑客', '青衣剑客踏浪邀战，剑尖始终停在你眉心三寸。', '斗法',
    choice('正面应战', '数十合后，江面尽是纵横气浪。', { reputation: 7, qi: -6, item: 'river-iron' }),
    choice('以道论剑', '杀机散去，你们交换了半卷心得。', { insight: 7, influence: 3 })),
  event('duel-demon-boar', '赤鬃妖豕', '赤鬃妖豕冲进灵田，獠牙上挂着碎裂阵旗。', '斗法',
    choice('斩妖护田', '妖豕伏诛，佃户送来珍藏灵谷。', { food: 22, reputation: 6, health: -5 }),
    choice('设阵驱赶', '妖豕被引向荒谷，双方皆免死伤。', { qi: -8, karma: 4, control: 3 })),
  event('duel-ambush', '夜林伏杀', '三名蒙面修士封住退路，他们显然准备已久。', '斗法',
    choice('雷霆破阵', '你从最强处撕开包围。', { health: -9, influence: 7, spiritStones: 16 }),
    choice('遁入影中', '你保存实力，也记住了领头人的气息。', { soul: -7, stability: 5 })),
  event('duel-challenge-seal', '宗门战帖', '金色战帖钉入门前石柱：三日后，擂台论高下。', '斗法',
    choice('揭帖赴战', '此战传遍四方，你的名号不再寂寂。', { reputation: 11, health: -7 }),
    choice('退帖问因', '战帖背后原是一桩资源误会。', { influence: 6, karma: 3 })),
  event('duel-mind-demon', '心魔借形', '对手忽然变成你的模样，连招式与迟疑都分毫不差。', '斗法',
    choice('胜过自己', '你斩碎旧日怯懦。', { stability: 9, insight: 6 }),
    choice('接纳自己', '镜像与你相融，识海恢复完整。', { soul: 12, karma: 4 })),
  event('duel-thunder-beast', '雷泽凶兽', '六足雷兽从泽中跃起，背脊电芒照亮百丈泥沼。', '斗法',
    choice('夺取雷角', '雷角落手，掌心仍有电弧跳跃。', { health: -10, item: 'thunder-horn', influence: 5 }),
    choice('引雷炼魂', '你借凶兽之雷洗练神魂。', { soul: -10, maxSoul: 8, stability: 5 })),
  event('duel-debt-collector', '旧债新仇', '一名散修认错了人，执意要你偿还十年前的灵石债。', '斗法',
    choice('以力服人', '误会在拳掌之间讲清了。', { reputation: -3, spiritStones: 10, karma: -3 }),
    choice('查清账册', '真正的欠债者浮出水面。', { influence: 8, reputation: 4 })),
  event('duel-fallen-guardian', '失控守傀', '古遗迹守傀重启，将每个靠近者都视作盗墓贼。', '斗法',
    choice('拆取核心', '守傀停转，一枚完好核心滚入手中。', { qi: -10, item: 'puppet-core' }),
    choice('改写禁令', '守傀安静跪下，成为此地新的守卫。', { soul: -8, control: 8 })),

  event('claim-spirit-spring', '无主灵泉', '两山之间涌出新泉，各方旗号已在谷口聚集。', '占地',
    choice('先立界碑', '界碑落地，灵泉暂归你名下。', { control: 8, spiritStones: 12, reputation: -2 }),
    choice('共议泉契', '你让出部分收益，换来长久安宁。', { influence: 9, karma: 5 })),
  event('claim-village-oath', '山民献契', '山民捧来血契，请你庇护村落免受邪修侵扰。', '占地',
    choice('收下血契', '契约带来服从，也带来沉重责任。', { control: 9, food: 18, karma: -2 }),
    choice('焚契立誓', '无血契亦可守护，此举深得人心。', { reputation: 9, karma: 7, influence: 5 })),
  event('claim-mine-collapse', '灵矿塌方', '新占矿脉突然塌陷，深处却透出更浓的灵光。', '占地',
    choice('强开深层', '你付出代价，挖出一批上品矿石。', { health: -8, spiritStones: 35, control: -5 }),
    choice('先救矿工', '矿脉暂封，人心却稳了。', { reputation: 8, control: 6, spiritStones: -8 })),
  event('claim-rival-banner', '敌旗越界', '邻境旗帜一夜间向前推进三里，正压在灵脉交汇处。', '占地',
    choice('拔旗推进', '边界向外推去，空气中仍留着杀气。', { influence: 8, control: -4, karma: -4 }),
    choice('阵前谈判', '你用一成矿税换回明确疆界。', { spiritStones: -12, control: 8, reputation: 4 })),
  event('claim-flood', '玄水改道', '暴涨玄水即将冲毁灵田，改道则会淹没一片荒村旧址。', '占地',
    choice('保住灵田', '粮仓无虞，但怨气在旧址聚集。', { food: 28, stability: -5, karma: -5 }),
    choice('疏水入泽', '你损失收成，却护住了两岸生灵。', { food: -15, karma: 9, reputation: 7 })),
  event('claim-ancient-map', '古疆残图', '残碑背后藏着旧朝疆图，一条废弃灵道直通北岭。', '占地',
    choice('沿图开拓', '旧路重开，商旅开始通行。', { influence: 12, food: -8, item: 'border-map' }),
    choice('封存残图', '过早扩张并非好事，你加固了现有边界。', { control: 12, stability: 4 })),
  event('claim-fox-clan', '狐族来使', '白狐衔玉而来，愿以山林药材换取一处安居之地。', '占地',
    choice('缔结山盟', '山林多了一群耳目，也多了一份牵挂。', { influence: 10, food: 12, karma: 4 }),
    choice('婉拒来使', '边界仍然清晰，白狐的目光却有些失望。', { control: 7, stability: 3 })),
  event('claim-earth-vein', '地脉翻身', '地底轰鸣如巨兽翻身，数处阵眼同时告急。', '占地',
    choice('亲镇阵眼', '你以道纹钉住地脉，三日白发。', { soul: -12, control: 15, reputation: 6 }),
    choice('迁民避灾', '损失无法避免，好在无人殒命。', { food: -12, spiritStones: -15, karma: 7 })),

  event('break-heavenly-gate', '天门一线', '雷云裂开一线天光，更高境界近在咫尺。', '突破',
    choice('迎雷而上', '你将雷霆视作登天阶。', { health: -8, insight: 8, reputation: 5 }),
    choice('守住灵台', '不追天光，只守此心。', { stability: 10, harmony: 8 })),
  event('break-ancestral-question', '古祖三问', '虚空传来三问：为何修道？为何争地？为何不退？', '突破',
    choice('答以本心', '答案没有对错，本心因此澄澈。', { harmony: 12, karma: 3 }),
    choice('沉默证道', '你以一身气机作答。', { soul: -8, maxSoul: 6 })),
  event('break-cracked-core', '道基生隙', '冲关余波在道基上留下一道细微裂隙。', '突破',
    choice('立刻弥合', '大量灵石化作粉尘，裂隙终于闭合。', { spiritStones: -20, health: 8, stability: 5 }),
    choice('以隙纳雷', '裂隙吞入雷光，危险中藏着新路。', { health: -9, insight: 11 })),
  event('break-world-whisper', '天地低语', '境界松动时，整片领地的风都在重复你的名号。', '突破',
    choice('回应天地', '你的意志沿地脉扩散。', { influence: 12, control: 7, soul: -7 }),
    choice('斩断回响', '名号归于寂静，道心不受外物牵扯。', { stability: 12, karma: 2 })),
  event('break-rival-observer', '故敌观礼', '昔日对手站在远峰，既未出手，也未离开。', '突破',
    choice('邀其护法', '一场旧怨在雷声中消解。', { reputation: 9, karma: 5 }),
    choice('任其旁观', '你的突破本就是最有力的回答。', { influence: 10, harmony: 5 })),
  event('break-soul-shedding', '魂蜕如蝉', '旧神魂如蝉蜕般剥落，新生灵识尚且脆弱。', '突破',
    choice('舍弃旧念', '过去远去，神魂轻盈而强大。', { maxSoul: 12, stability: -5 }),
    choice('收存魂蜕', '你把来路炼成一枚护魂秘宝。', { item: 'soul-sheath', soul: 8 })),
  event('break-dao-rain', '道雨洗山', '冲关气息引来七色道雨，领内草木一夜抽芽。', '突破',
    choice('独沐道雨', '七色灵机尽归一身。', { insight: 10, qi: 15, karma: -2 }),
    choice('泽被领民', '道雨落遍田野，众生同庆。', { food: 30, reputation: 10, karma: 6 })),
];

export const ITEMS: GameItem[] = [
  { id: 'soul-pill', name: '养魂丹', category: '丹药', rarity: '凡', description: '温养识海的青色丹丸。', consumable: true, effect: { soul: 18, stability: 4 } },
  { id: 'healing-pill', name: '回春丹', category: '丹药', rarity: '凡', description: '止血生肌，山门常备。', consumable: true, effect: { health: 24 } },
  { id: 'qi-pill', name: '聚气丹', category: '丹药', rarity: '凡', description: '迅速补足亏空灵气。', consumable: true, effect: { qi: 28 } },
  { id: 'clarity-tea', name: '明心茶', category: '丹药', rarity: '玄', description: '一盏洗去心湖尘埃。', consumable: true, effect: { harmony: 12, stability: 8 } },
  { id: 'thunder-marrow', name: '雷髓液', category: '丹药', rarity: '地', description: '雷泽深处凝成的灵液。', consumable: true, effect: { maxSoul: 10, health: -5 } },
  { id: 'longevity-fruit', name: '青寿果', category: '丹药', rarity: '天', description: '传说可添一纪寿数。', consumable: true, effect: { health: 40, soul: 20 } },
  { id: 'river-iron', name: '沉江铁', category: '道材', rarity: '玄', description: '沉在大江底三百年的寒铁。', consumable: true, effect: { spiritStones: 24 } },
  { id: 'star-silver', name: '星银砂', category: '道材', rarity: '玄', description: '能引导细微道韵的银砂。', consumable: true, effect: { insight: 8 } },
  { id: 'thunder-horn', name: '雷兽独角', category: '道材', rarity: '地', description: '蕴含未散的雷泽凶威。', consumable: true, effect: { qi: 20, influence: 4 } },
  { id: 'turtle-rubbing', name: '玄龟甲拓', category: '道材', rarity: '玄', description: '残缺却古老的天然纹图。', consumable: true, effect: { insight: 10, harmony: 3 } },
  { id: 'void-crystal', name: '太虚晶', category: '道材', rarity: '天', description: '凝视久了仿佛会坠入其中。', consumable: true, effect: { maxSoul: 14, stability: -3 } },
  { id: 'dragon-bone', name: '地龙骨', category: '道材', rarity: '地', description: '可用于稳固山川阵眼。', consumable: true, effect: { control: 14 } },
  { id: 'cloud-sword', name: '流云剑', category: '法器', rarity: '玄', description: '剑随意动，迅若流云。', consumable: true, effect: { qi: 18, reputation: 3 } },
  { id: 'five-thunder-seal', name: '五雷印', category: '法器', rarity: '地', description: '印落时有五雷齐鸣。', consumable: true, effect: { influence: 10, soul: -4 } },
  { id: 'mountain-cauldron', name: '镇岳鼎', category: '法器', rarity: '地', description: '鼎虽三寸，落地重逾山岳。', consumable: true, effect: { control: 12, health: 10 } },
  { id: 'soul-lamp', name: '照魂灯', category: '法器', rarity: '玄', description: '灯焰可照见神魂暗伤。', consumable: true, effect: { soul: 12, stability: 10 } },
  { id: 'puppet-core', name: '玄傀核心', category: '法器', rarity: '地', description: '仍在规律跳动的机关核心。', consumable: true, effect: { control: 8, influence: 6 } },
  { id: 'storm-banner', name: '召雷幡', category: '法器', rarity: '天', description: '展开便令百里云聚。', consumable: true, effect: { insight: 12, reputation: 6 } },
  { id: 'border-map', name: '古疆残图', category: '秘宝', rarity: '玄', description: '标有数条失传的地脉暗道。', consumable: true, effect: { influence: 10, food: 8 } },
  { id: 'soul-sheath', name: '旧魂蝉蜕', category: '秘宝', rarity: '地', description: '保存着突破前的完整魂息。', consumable: true, effect: { soul: 20, stability: 7 } },
  { id: 'dao-jade', name: '无字道玉', category: '秘宝', rarity: '天', description: '每个人都能从中看见不同道纹。', consumable: true, effect: { insight: 18, harmony: 10 } },
  { id: 'land-seal', name: '山河令', category: '秘宝', rarity: '地', description: '持令者可调动一方地气。', consumable: true, effect: { control: 15, influence: 8 } },
  { id: 'karma-thread', name: '因果红绳', category: '秘宝', rarity: '玄', description: '系住一段将断未断的缘法。', consumable: true, effect: { karma: 10, reputation: 4 } },
  { id: 'heaven-key', name: '天门钥', category: '秘宝', rarity: '天', description: '不知开启哪一扇门的青铜古钥。', consumable: true, effect: { insight: 20, maxSoul: 8 } },
];

export const ENDINGS: Ending[] = [
  { id: 'death', title: '雷殒荒丘', rank: '凡', description: '道纹随风熄灭，唯有焦土记得你曾逆雷而行。' },
  { id: 'oldAge', title: '坐化听雨', rank: '玄', description: '寿数终尽，你在檐下听完最后一场雨，含笑散道。' },
  { id: 'swordSupreme', title: '一剑开天', rank: '天', description: '万里雷云被一剑分开，天下剑修皆尊你为道君。' },
  { id: 'spellSupreme', title: '万法归宗', rank: '天', description: '诸法如星辰环绕，你一念便令天地改换法则。' },
  { id: 'bodySupreme', title: '不灭道躯', rank: '天', description: '山河会朽，而你的道躯与世长存。' },
  { id: 'soulSupreme', title: '神游太虚', rank: '天', description: '神魂越过天门，诸界都留下你的清晰回响。' },
  { id: 'conqueror', title: '山河共主', rank: '地', description: '十二道旗插遍群山，疆域内无人不知你的法令。' },
  { id: 'patternSage', title: '万纹天书', rank: '地', description: '你将一生道纹汇为天书，后来者循此再开大道。' },
  { id: 'soulAscendant', title: '魂灯不灭', rank: '地', description: '肉身归尘，神魂却如长夜明灯，千年不熄。' },
  { id: 'magnate', title: '富甲仙域', rank: '玄', description: '商路与灵矿织成另一种疆域，连大宗也向你借石。' },
  { id: 'benevolent', title: '万家生祠', rank: '地', description: '你未称尊，众生却在每一座村镇为你点起长明灯。' },
  { id: 'wanderer', title: '云外散人', rank: '玄', description: '你放下疆土与名号，从此只在云海传说中偶现。' },
];

export const ORIGINS: Record<OriginId, { name: string; description: string }> = {
  mountain: { name: '山村遗孤', description: '体魄坚韧，知晓土地与饥寒。' },
  clan: { name: '世家旁支', description: '携灵石入道，也背负家族目光。' },
  wanderer: { name: '江湖散修', description: '见惯人心，声望与因果皆由己取。' },
  fallen: { name: '破宗余脉', description: '守着残卷与一段未雪旧恨。' },
};

export const VOWS: Record<VowId, { name: string; description: string }> = {
  guard: { name: '守土安民', description: '愿以一身道法护住身后灯火。' },
  freedom: { name: '逍遥天地', description: '不受宗门、疆域与旧法束缚。' },
  supreme: { name: '问鼎至高', description: '既见天门，便要站到群峰之上。' },
  mercy: { name: '止戈济世', description: '修道不是为了让弱者再次低头。' },
};

export const PATH_INFO: Record<DaoPath, { title: string; description: string; glyph: string }> = {
  剑: { title: '剑途', description: '锋锐决绝，斗法与道纹威力更强。', glyph: '剣' },
  法: { title: '法途', description: '驾驭雷法，灵气与神魂相互增益。', glyph: '法' },
  体: { title: '体途', description: '以身为器，血气雄浑，久战不退。', glyph: '躯' },
  神: { title: '神途', description: '神游物外，魂力成长冠绝诸途。', glyph: '神' },
};
